# Generated by Django 4.2 on 2024-03-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_checkout_address_alter_checkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='cart.cart'),
        ),
    ]
