# Generated by Django 4.2 on 2024-03-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address',
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
