# Generated by Django 4.2 on 2024-03-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='cart.cart'),
        ),
    ]
