# Generated by Django 4.2 on 2024-03-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_cart_order_complted'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
