# Generated by Django 4.2 on 2024-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_checkout_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
