# Generated by Django 4.2 on 2024-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_checkout_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
