# Generated by Django 4.2 on 2024-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_remove_checkout_cart_checkout_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
