# Generated by Django 4.2 on 2024-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_checkout_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
