# Generated by Django 4.2 on 2024-04-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_alter_checkout_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
