# Generated by Django 4.2 on 2024-04-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_alter_checkout_address_alter_checkout_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
