# Generated by Django 4.2 on 2024-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('WAITING FOR SHIPPING', 'waiting for shipping'), ('PRODUCT ON THE WAY', 'product on the way'), ('OUT OF DELIVERY', 'out of delivery'), ('DELIVERED', 'delivered')], default='WAITING FOR SHIPPING', max_length=50),
        ),
    ]
