# Generated by Django 4.2 on 2024-04-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_orders_alter_order_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
